# Generated by Django 5.0 on 2025-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chatmessage_role_alter_conversation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', upload_to='profile_pics'),
        ),
    ]
