# Generated by Django 5.0 on 2025-01-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
