# Generated by Django 5.0 on 2025-01-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_conversation_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=50),
        ),
    ]
