# Generated by Django 4.2 on 2025-01-30 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 23, 0, 45, 176580, tzinfo=datetime.timezone.utc)),
        ),
    ]
