# Generated by Django 4.2 on 2025-01-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatmessage_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='expires_at',
        ),
    ]
